import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by scripts/convert-gitbook.mjs from the GitBook SUMMARY.md.
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: "index", label: "🏠 ยินดีต้อนรับสู่ OpenThaiGPT 1.6 และ OpenThaiGPT R1"},
    {type: 'doc', id: "openthairag", label: "📚 OpenThaiRAG"},
    {type: 'doc', id: "web-demo", label: "🎇 Web Demo!"},
    {type: 'doc', id: "colab-demo", label: "▶️ Colab Demo!"},
    {type: 'doc', id: "openthaigpt-1.0.0-less-than-8-apr-2024-greater-than", label: "🔥 OpenThaiGPT 1.0.0 <8 Apr 2024>"},
    {type: 'doc', id: "sponsors", label: "❤️ องค์กรที่ร่วมสนับสนุน (Sponsors)"},
    {type: 'doc', id: "volunteer", label: "🤟 ทีมอาสาสมัคร (Volunteer)"},
    {type: 'doc', id: "rules", label: "กฎกติกาความร่วมมือ (Rules)"},
    {type: 'doc', id: "join-us", label: "ร่วมกับเรา (Join Us)"},
    {type: 'doc', id: "license", label: "License"},
    {
      type: 'category',
      label: "Previous Versions and Resources",
      link: {type: 'doc', id: "previous-versions-and-resources/index"},
      items: [
        {
          type: 'category',
          label: "💻 Released Code / Colabs",
          link: {type: 'doc', id: "previous-versions-and-resources/released-code-colabs/index"},
          items: [
            {type: 'doc', id: "previous-versions-and-resources/released-code-colabs/pretraining-llm", label: "Pretraining LLM"},
            {type: 'doc', id: "previous-versions-and-resources/released-code-colabs/instructgpt-finetuning", label: "🆕 InstructGPT Finetuning"},
            {type: 'doc', id: "previous-versions-and-resources/released-code-colabs/reinforcement-learning-with-human-feedback-rlhf", label: "Reinforcement Learning with Human Feedback (RLHF)"},
          ],
        },
        {type: 'doc', id: "previous-versions-and-resources/dataset-chat", label: "😍 การช่วยกันสร้าง Dataset สนทนา Chat ภาษาไทย!"},
        {type: 'doc', id: "previous-versions-and-resources/released-datasets-14-04-23", label: "📄 Released Datasets (14/04/23)"},
        {type: 'doc', id: "previous-versions-and-resources/released-openthaigpt-pip-python-library-less-than-0.1.1-greater-than-26-05-23", label: "📦 Released OpenThaiGPT Pip Python Library <0.1.1> (26/05/23)"},
        {type: 'doc', id: "previous-versions-and-resources/released-openthaigpt-7b-less-than-1.0.0-beta-greater-than-16-08-23", label: "🔥 Released OpenThaiGPT 7b <1.0.0-beta> (16/08/23)"},
        {type: 'doc', id: "previous-versions-and-resources/released-openthaigpt-13b-less-than-1.0.0-beta-greater-than-20-12-23", label: "🔥 Released OpenThaiGPT 13b <1.0.0-beta> (20/12/23)"},
        {type: 'doc', id: "previous-versions-and-resources/roadmap", label: "แผนการดำเนินงาน Roadmap"},
        {
          type: 'category',
          label: "Open Resources",
          link: {type: 'doc', id: "previous-versions-and-resources/open-resources/index"},
          items: [
            {type: 'doc', id: "previous-versions-and-resources/open-resources/free-working-datasets", label: "🆕 Free Working Datasets"},
            {type: 'doc', id: "previous-versions-and-resources/open-resources/related-paper-knowledge", label: "Related Paper / Knowledge"},
            {type: 'doc', id: "previous-versions-and-resources/open-resources/computing-resources", label: "Computing Resources"},
          ],
        },
        {
          type: 'category',
          label: "Previous Events",
          link: {type: 'doc', id: "previous-versions-and-resources/previous-events/index"},
          items: [
            {type: 'doc', id: "previous-versions-and-resources/previous-events/openthaigpt-meet-up-2", label: "🥳 OpenThaiGPT Meet Up #2"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/finetune-8-apr", label: "🆕 อัพเดท! จากทีม Finetune (8 Apr)"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/core-team-volunteer-meeting-19-march-15-30", label: "Core-team Volunteer Meeting 19 March 15:30"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/finetuning-rlhf-volunteer-event-18-march", label: "Finetuning / RLHF Volunteer Event (18 March)"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/safety-net-volunteer-event-12-march-19-00-19-45", label: "Safety Net Volunteer Event (12 March 19:00-19:45)"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/pre-training-volunteer-event-11-march-19-00-20-15", label: "Pre-training Volunteer Event (11 March 19:00-20:15)"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/volunteer-meetup-1-zoom-5-march-13-00", label: "Volunteer Meetup #1 (Zoom) 5 March 13:00"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/first-meet-up-25-feb-2023", label: "First Meet Up (25 Feb 2023)!"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/released-models-version-less-than-0.1.0-beta-greater-than-16-05-23", label: "🔥 Released Models Version <0.1.0-beta> (16/05/23)"},
            {type: 'doc', id: "previous-versions-and-resources/previous-events/released-models-version-less-than-1.0.0-alpha-greater-than-03-08-23", label: "🔥 Released Models Version <1.0.0-alpha> (03/08/23)"},
          ],
        },
        {type: 'doc', id: "previous-versions-and-resources/chatgpt-how-to-build-chatgpt", label: "ChatGPT สร้างขึ้นมาได้อย่างไร (How to build ChatGPT?)"},
        {type: 'doc', id: "previous-versions-and-resources/openthaigpt-version-1.0", label: "OpenThaiGPT Version 1.0"},
        {type: 'doc', id: "previous-versions-and-resources/openthaigpt-1.5", label: "OpenThaiGPT 1.5"},
      ],
    },
  ],
};

export default sidebars;
